### ISSUE TITLE
Mapa com localização das empresas do B+P

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/aval_Brasil_mais_Prod#14]
Pegar 6,5mil as empresas do B+P, na base já enriquecida com informações da RAIS.

Ver com o @Mathscosta se o merge com a RAIS trouxe os campos de  endereço. 

Geolocalizar os endreços. 

Potencialmente podemos ter 2 tipos  de mapas: 

Colocaração Por município, com as cores representando os municípios que tiveram inscrições de vários tipos.

Por pontos contendo a localização das empresas, pintados de diferentes cores em função do status dela. 

@JuliaAkaishi PSC

@damatadaniel , detalhe mais o que tinha pensado a este respeito

**Comment by damatadaniel** [comment]
Pensei em dois mapas, ambos utilizando a malha dos estados brasileiros:


(a) 1 contendo o ponto da localização de cada empresa (com cores distintas para as 4 categorias de empresas)

(b) outro com tonalidades distintas por estado mostrando a quantidade de empresas inscritas no site do programa



________________________________

**Comment by Mathscosta** [comment]
Acabei de dar push na base.

Endereço da base de cadastrados pareada com a Rais: "1data/cadastro_rais.rds"

**Comment by joaofm91** [comment]
@lucasmation  e @damatadaniel  o mapa (1) é assim ? e o segundo seria com o shape dos municipios, certo?
![image](https://user-images.githubusercontent.com/12373090/37210823-c7fbe958-2388-11e8-8261-2c4565b0ec49.png)

**Comment by lucasmation** [comment]
João,

legal, mas as categorias de empresa não são estas.

É o cruzamento de elegibilidade com tratada. Tem uma variável na base que
tem estas duas infos juntas

2018-03-09 10:58 GMT-03:00 João Victor Freitas Machado <
notifications@github.com>:

**Comment by joaofm91** [comment]
essa variável ?
![image](https://user-images.githubusercontent.com/12373090/37211482-ceb251fe-238a-11e8-98a7-112df46d1f53.png)

**Comment by lucasmation** [comment]
isso

2018-03-09 11:13 GMT-03:00 João Victor Freitas Machado <
notifications@github.com>:

**Comment by joaofm91** [comment]
(2) mapa com o preenchimento dos shapes dos municípios opção 1:
![image](https://user-images.githubusercontent.com/12373090/37215606-308cadaa-2397-11e8-98fa-c3fe47496c11.png)
@lucasmation  e @damatadaniel

**Comment by joaofm91** [comment]
(2) opção 2:
![image](https://user-images.githubusercontent.com/12373090/37215831-d2eb3daa-2397-11e8-99cc-86cd28a1172a.png)

**Comment by lucasmation** [comment]
joao, faz um mapa só com os estados do brasil, com fundo branco, sem estas
figuras do google por trás e só com os pontos (sem as shades

2018-03-09 12:46 GMT-03:00 João Victor Freitas Machado <
notifications@github.com>:

**Comment by joaofm91** [comment]
nesse estilo, @lucasmation ? ou sem pegar da fonte google?
![image](https://user-images.githubusercontent.com/12373090/37223845-9279723c-23b0-11e8-8526-88d016915365.png)

**Comment by lucasmation** [comment]
sem google, pega um shape,

2018-03-09 15:44 GMT-03:00 João Victor Freitas Machado <
notifications@github.com>:

**Comment by joaofm91** [comment]
Opção com shape @lucasmation  e @damatadaniel :
![image](https://user-images.githubusercontent.com/12373090/37307346-67ae5336-2619-11e8-96a6-55ab66f3ba9f.png)

**Comment by joaofm91** [comment]
opção (2)
![image](https://user-images.githubusercontent.com/12373090/37307497-ee26d3ac-2619-11e8-9923-8b244c97d637.png)

**Comment by joaofm91** [comment]
com google apenas com a linha tracejada dos municípios:
![image](https://user-images.githubusercontent.com/12373090/37307549-120ecbf8-261a-11e8-9270-5bdfb1e6f2cf.png)

**Comment by joaofm91** [comment]
utilizando tema **theme_tufte()**:
![image](https://user-images.githubusercontent.com/12373090/37307942-39d8adf6-261b-11e8-93b2-6d6d7686e62d.png)

**Comment by damatadaniel** [comment]
João, poderia fazer esse último mapa somente com duas categorias: tratado e não-tratado?


________________________________________

**Comment by joaofm91** [comment]
@damatadaniel  só para tratado e não tratado:
![image](https://user-images.githubusercontent.com/12373090/37344722-eaf9d4aa-26a9-11e8-8440-816989148bb7.png)
